x = (input(''))
zero = x.count('0')
one = x.count('1')
two = x.count('2')
three = x.count('3')
four = x.count('4')
five = x.count('5')
six = x.count('6')
seven = x.count('7')
eight = x.count('8')
nine = x.count('9')
print('0 dan 9 gacha bo\'lgan raqamlar soni: ',zero+one+two+three+four+five+six+seven+eight+nine)
